config/routes.rb
Rails.application.routes.draw do

  resources :posts
  root to: redirect('/home')

  get 'home', to: 'home#show'

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.slim
h1 Users

table
  thead
    tr
      | Users
      th

  tbody
    - @users.each do |user|
      tr
        td = user.email

app/views/layouts/application.html.slim
html xmlns="http://www.w3.org/1999/xhtml"
  /![if lt IE 7 ] <html class="ie ie6" lang="en"
  /![if IE 7 ] <html class="ie ie7" lang="en"
  /![if IE 8 ] <html class="ie ie8" lang="en"
  /! [if (gte IE 9)|!(IE)]><!
  html lang="en"
    /! <![endif]
    head
      meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
      title Boscaiola
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag 'application', 'data-turbolinks-track' => true

      /= stylesheet_link_tag 'base.css', media: 'screen'
      /= stylesheet_link_tag 'skeleton.css', media: 'screen'
      /= stylesheet_link_tag 'layout.css', media: 'screen'
      /= stylesheet_link_tag 'child.css', media: 'screen'
      /![if (IE 6)|(IE 7)]
                | <link rel="stylesheet" href="css/ie.css" type="text/css" media="screen" /
      /![if lt IE 9]
                | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script

      /= javascript_include_tag 'jquery-1-8-2.js', 'data-turbolinks-track' => true
      /= javascript_include_tag 'default.js', 'data-turbolinks-track' => true
      /= javascript_include_tag 'jquery.easing.1.3.js', 'data-turbolinks-track' => true
      /= javascript_include_tag 'jquery.carousel.js', 'data-turbolinks-track' => true
      /= javascript_include_tag 'jquery.color.animation.js', 'data-turbolinks-track' => true
      /
      //! color pickers
      /= stylesheet_link_tag 'colorpicker.css', media: 'screen'
      /= javascript_include_tag 'colorpicker.js', 'data-turbolinks-track' => true
      //! end of color pickers
      = csrf_meta_tags
    body
      p.notice= notice
      p.alert= alert
      .page-wrapper
        .slug-pattern
          .overlay
            .slug-cut
        .header
          .nav
            .container
              /! Standard Nav (x >= 768px)
              .standard
                .five.column.alpha
                  .logo
                    a href="index.html"
                      img src="#{asset_path 'logo.png'}"
                /! Large Logo
                .eleven.column.omega.tabwrapper
                  .menu-wrapper
                    ul.tabs.menu
                      li
                        a href="index.html"
                          span Home
                        ul.child
                          li
                            a href="index-nivo.html"  Alternate
                          li
                            a href="index-async.html"  Alternate 2
                          li
                            a href="index-flex.html"  Alternate 3
                          li
                            a href="index-style-5.html"  Alternate 4
                          li
                            a href="index-style-6.html"  Alternate 5
                      li
                        a href="#"  Pages
                        ul.child
                          li
                            a href="index.html"  Homepages
                            ul
                              li
                                a href="index-nivo.html"  Alternate
                              li
                                a href="index-async.html"  Alternate 2
                              li
                                a href="index-flex.html"  Alternate 3
                              li
                                a href="index-style-5.html"  Alternate 4
                              li
                                a href="index-style-6.html"  Alternate 5
                          li
                            a href="portfolio-standard-3.html"  Portfolios
                            ul
                              li
                                a href="portfolio-standard-1.html"  Standard 1 Column
                              li
                                a href="portfolio-standard-2.html"  Standard 2 Columns
                              li
                                a href="portfolio-standard-3.html"  Standard 3 Columns
                              li
                                a href="portfolio-standard-3-alternate.html"  Standard 3 Alternate
                              li
                                a href="portfolio-standard-4.html"  Standard 4 Columns
                              li
                                a href="portfolio-standard-5.html"  Standard 5 Columns
                              li
                                a href="portfolio-info.html"  Info Style
                              li
                                a href="portfolio-basic-1.html"  Basic Style
                          li
                            a href="blog.html"  Blog Pages
                            ul
                              li
                                a href="blog.html"  Standard Blog
                              li
                                a href="blog-style-2.html"  Blog Style 2
                              li
                                a href="blog-style-3.html"  Blog Style 3
                              li
                                a href="blog-style-4.html"  Blog Style 4
                              li
                                a href="blog-post.html"  Blog Post (Single)
                          li
                            a href="contact.html"  Contact Pages
                            ul
                              li
                                a href="contact.html"  Contact
                              li
                                a href="contact-style-2.html"  Contact 2
                          li
                            a href="sidebar-right.html"  Sidebar Right
                          li
                            a href="sidebar-left.html"  Sidebar Left
                      li
                        a.active href="blog.html"  Blog
                        ul.child
                          li
                            a href="blog.html"  Standard Blog
                          li
                            a href="blog-style-2.html"  Blog Style 2
                          li
                            a href="blog-style-3.html"  Blog Style 3
                          li
                            a href="blog-style-4.html"  Blog Style 4
                          li
                            a href="blog-post.html"  Blog Post (Single)
                      li
                        a href="portfolio-standard-3.html"
                          | Portfolio
                        ul.child
                          li
                            a href="portfolio-standard-1.html"  Standard 1 Column
                          li
                            a href="portfolio-standard-2.html"  Standard 2 Columns
                          li
                            a href="portfolio-standard-3.html"  Standard 3 Columns
                          li
                            a href="portfolio-standard-3-alternate.html"  Standard 3 Alternate
                          li
                            a href="portfolio-standard-4.html"  Standard 4 Columns
                          li
                            a href="portfolio-standard-5.html"  Standard 5 Columns
                          li
                            a href="portfolio-info.html"  Info Style
                          li
                            a href="portfolio-basic-1.html"  Basic Style
                      li
                        a href="contact.html"
                          | Contact
              /! Standard Nav Ends, Start of Mini
              .mini
                .twelve.column.alpha.omega.mini
                  .logo
                    a href="index.html"
                      img src="#{asset_path 'logoMINI.png'}"
                /! Small Logo
                .twelve.column.alpha.omega.navagation-wrapper
                  select.navagation
                    option selected="selected" value=""  Site Navagation
          /! Start of Mini Ends
          .shadow
          .container
            .page-title
              .rg
              h1 Our Blog
        .body
          .body-round
          .body-wrapper
            .side-shadows
            .content
            = yield
    /! Blog Ends

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
.container
  .twelve.columns
    .blog.style-4
      - @posts.each do |post|
        .border
          .meta
            p = post.created_at
          img.scale-with-grid src="#{asset_path 'portfolio-large-mnt.jpg'}"
          a.link href="blog-post.html"
        .description
          h5
            a href="blog-single.html"  Standard Blog Post
          .info
            | POSTED BY:
            a href="#"  SupremeGeneral
            span \
            | COMMENTS:
            a href="#"  2 Comments
            span \
            | CATS:
            a href="#"  Category 1
          p = post.description
          a href=post_path(post)
            span More
          a href=edit_post_path(post)
            span Edit
        .clear

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p
  strong Description:
  = @post.description

= link_to 'Edit', edit_post_path(@post)
'|
= link_to 'Back', posts_path